version: '3'

services:
  user_service:
    build:
      context: ./services/user_service
      container_name: user_service
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DATABASE_URL=postgres://user_service_user:password@db:5432/user_service_db
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: user_service_db
    environment:
      POSTGRES_USER: user_service_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_service_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  registration_service:
    build:
      context: ./services/registration_service
    ports:
      - "8002:8000"
    depends_on:
      - db
      - redis

  exam_service:
    build:
      context: ./services/exam_service
    ports:
      - "8003:8000"
    depends_on:
      - db
      - redis

  notification_service:
    build:
      context: ./services/notification_service
    ports:
      - "8004:8000"
    depends_on:
      - db
      - redis

  grading_service:
    build:
      context: ./services/grading_service
    ports:
      - "8005:8000"
    depends_on:
      - db
      - redis

  admin_service:
    build:
      context: ./services/admin_service
    ports:
      - "8006:8000"
    depends_on:
      - db
      - redis

  redis:
    image: redis

volumes:
  postgres_data: